export const GET_EXPENSE_DETAILS = 'GET_EXPENSE_DETAILS';
export const SET_LOADER_TRUE = 'SET_LOADER_TRUE';
export const SET_LOADER_FALSE = 'SET_LOADER_FALSE';
export const SET_ERROR_STATE = 'SET_ERROR_STATE';
